Vagrant.configure(2) do |config|
    config.vm.box = "kalilinux/rolling"
    config.vm.hostname = "kali"
    config.vm.provider "virtualbox" do |vb|
        vb.cpus = 3
        vb.name = "kali_nmap"
        vb.memory = 2048
        vb.gui = false
    end
end
